[build]
  functions = "apps/react/netlify/functions"
[functions]
  external_node_modules = ["express", "@libsql/client"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
[[redirects]]
  from = "/s/*"
  to = "/.netlify/functions/s/:splat"
  status = 200
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200